select COUNT (*) COUNTDEÐERÝ, SUM (TOTALPRICE) SUMDEÐERÝ, AVG(AMOUNT),AVG(TOTALPRICE)
from SALES
where CITY = 'BAYBURT' 

-- BAYBURT ÞEHRÝÝ FÝLTRELEYÝP  TÜM SATIRLARI SAYIP BÝR KOLONDA DEÐERÝNÝ VERÝYOR , SUM DA TOTALPRÝCE LARI TOPLATIP BAÞKA BÝR KOLONDA YAZIYOR AVG DE ORTLAMAYI 
--ALIYOR. YANINDAKÝ COUNTDEÐERÝ GÝBÝ ÝSÝMLER KOLONLARIN BANA ÇIKTI OLARAK VERDÝÐÝ TABLONUN KOLONUNUN ADI OLUYOR . BAÞINA 'AS ' DE GETÝREBÝLÝRSÝN

select COUNT (*) AS COUNTDEÐERÝ, SUM (TOTALPRICE) SUMDEÐERÝ, AVG(AMOUNT),AVG(TOTALPRICE)
from SALES
where CITY = 'BAYBURT' 

--AS EKLENMÝÞ HALÝ


SELECT *,
       (SELECT SUM(TOTALPRICE) FROM SALES) AS count_deðeri
FROM SALES;

-- BURADA TÜM ÇIKTILARIN TOTAL PRÝCE LARI TOPLAYIP ORJÝNAL TABLODADA COUNTDEÐERÝ DÝYE KOLON AÇIP ONA YAZIYOR -TÜM DEÐERLER AYNI-



--ÇIKTIDAKÝ TABLOLARDA KOLON ADINI DEÐÝÞTÝREBÝLÝRSÝN 
SELECT 
CITY CITYNAME, FICHENO FISHENUMBER
FROM SALES
ORDER BY CITY 


SELECT 
CITY,DISTRICT,
COUNT(*) SATIRSAYISI, SUM(TOTALPRICE) TOPLAMCIRO, MAX(TOTALPRICE) ENYUKSEKFIYAT, MIN (TOTALPRICE) ENDUSUKFIYAT 
FROM SALES
--WHERE CITY IN ('ÝSTANBUL', 'BAYBURT')
GROUP BY CITY ,DISTRICT
ORDER BY CITY , DISTRICT

-- ÝSTANBUL VE BAYBURTU GRUP YAPIYOR ÝKÝSÝNÝN DE KENDÝ ÝÇÝNDE ÝSTANBULUN SATIR SAYISI CE TOPLAM CÝR ALTINDA DA DÝÐER SATIR BAYBURT SATIR VE TOPLAM CÝRO VERÝR.
--WHERE ÞARTI KALKSA TÜM ÞEHÝRLER ÝÇÝN YAPAR








--ALIÞTIRMALAR


--Bir maðazanýn günlük bazlý satýþ rakamýný getirme
SELECT 
CONVERT(DATE, DATE_) AS DATE__, SUM (TOTALPRICE) TOTALSALE
FROM SALES
WHERE CITY = 'ÝSTANBUL'

GROUP BY CONVERT (DATE,DATE_)
ORDER BY 1--CONVERT (DATE,DATE_) , DATE__

--DATE_ deðerinde saat de olduðu için sadece date e çevirdik CONVERT ile gruplamayý da yeni date e göre yaptýk.
-- DATE__ YENÝ OLUÞAN GROUP BY da çalýþmaz ama order by da çalýþýr


SELECT 
CITY , SUM (TOTALPRICE) TOTALPRICE_,COUNT(*) TOTALSALE
FROM SALES
WHERE CONVERT(DATE,DATE_) = '2019-04-22'
--WHERE DATE_ BETWEEN '2019-04-22 00:00:00' AND '2019-04-22 23:59:59'

GROUP BY CITY
ORDER BY TOTALSALE DESC--1--CITY,

--burada herhangi bir günde tüm maðazzzalarda ne kadar ürün satýlmýþ ve ne kadar tutmuþ onu getiren kod