SELECT
([NAMESURNAE],[PHONENUM], [TCNO])
FROM
CUSTOMER
--sadece isim soyisim , telefon ve tc gelir 

SELECT
*
FROM
CUSTOMER
--tüm tabloyu getirir


TRUNCATE TABLE CUSTOMER
--tüm tablonun verilerini siler


INSERT INTO CUSTOMER
([NAMESURNAE], [GENDER], [BIRTHDATE], [CITY], [TOWN], [PHONENUM], [TCNO])
VALUES
('Aleyna erkul', 'K' , '1916-08-10' , 'Bayburt', 'Tahbur' , '5548513741' ,'48360628368'),
('Gökhan AK', 'E' , '1916-08-10' , 'DİYARBAKIR', 'merkez' , '5548513741' ,'48360628368')
--TABLOYA VERİ EKLER

UPDATE CUSTOMER
SET COUNTRY = 'TÜRKİYE'
--TÜM COUNTRY KOLONLARINI TÜRKİYE YAPAR

UPDATE CUSTOMER
SET AGE = DATEDIFF(YEAR, BIRTHDATE,GETDATE())
--TÜM TABLONUN AGE KOLONLARINA HESAPLAMA YAPAR

SELECT 
*,DATEDIFF(YEAR, BIRTHDATE,'2024-05-08')
FROM CUSTOMER

--DATEDIFF KOMUTU İLE YAŞ HESAPLAR HER KOLONUN

DELETE FROM CUSTOMER
-- TÜM VERİLERİ SİLER TRUNCATE İSE TABLONUN İLK HALİNE GERİ GİDER AYNI AMA ID DEĞİŞİKLİK OLUR







---WHERE KOMUTU

UPDATE CUSTOMER
SET CITY = 'İSTANBUL'
WHERE ID = '3' OR ID = '4';
-- BURADA MESELA ID Sİ 3 VE 4 OLAN SATIRLARIN CITY KOLONLARI ARTIK İST OLDU



SELECT * FROM CUSTOMER
WHERE AGE > 30

-- A-YAŞI 30 DAN BÜYÜK OLANLARI GETİRİR


SELECT * FROM CUSTOMER
WHERE GENDER = 'K'

--GENDER K OLANLARI GETİRİR


SELECT * FROM CUSTOMER
WHERE NAMESURNAE LIKE '%E%'

--namenurname karşılığında içerinde E geçen kolonları getirir sadece




--ŞEHRİ İSTANBUL VE YAŞI 30 OLAN KİŞİLER
SELECT * FROM CUSTOMER 
WHERE CITY= 'İSTANBUL' AND AGE = 30

SELECT * FROM CUSTOMER 
WHERE GENDER = 'K' AND AGE < 30


SELECT * FROM CUSTOMER 
WHERE CITY = 'İSTANBUL' AND TOWN = 'BÜYÜKÇEKMECE' OR TOWN = 'SARIYER'

-- BU DURUMDA İSTANBUL- BÜYÜKÇEKMECE VE TOWNU SARIYER OLAN(yani ankara sarıyer de gelir) TÜM KULLANICILAR GELİR

SELECT * FROM CUSTOMER 
WHERE CITY = 'İSTANBUL' AND (TOWN = 'BÜYÜKÇEKMECE' OR TOWN = 'SARIYER')

--BU DUURMDA İSTANBUL-BÜYÜKÇEKMECE VE İSTANBUL-SARIYER SADECE GELİR

UPDATE CUSTOMER 
SET AGEGROUP = 'GENÇ'
WHERE AGE BETWEEN 20 AND 40

--YAŞI 20 İLE 40 OLANLARI GENÇ OLARAK İŞARETLEDİK


DELETE FROM CUSTOMER
WHERE CITY = 'İZMİR'

--TABLODAKİ TÜM ŞEHRİ İZMİR OLANLARI SİLER 

SELECT DISTINCT CITY FROM CUSTOMER
ORDER BY CITY DESC

 -- BU KOMUT CİTY KOLONLARINI TEKRAR ETMEDEN VE Z DEN A YA (BÜYÜKTEN KÜÇÜĞE)DOĞRU SIRALAYARAK VERİR

 SELECT DISTINCT * FROM CUSTOMER
ORDER BY AGE ASC

--BU DA TAM TERSİ A DAN Z YE(KÜÇÜKTEN BÜYÜĞE) SIRALRA ŞEHİRLERİ

SELECT * FROM CUSTOMER
ORDER BY NAMESURNAE

--BU ŞEKİLDE DE A DAN Z YE SIRALAR.ORDER BY IN DEFAULT KULLANIMINDA ASC OLARK ÇALIŞIR

SELECT * FROM CUSTOMER
ORDER BY NAMESURNAE ASC, CITY DESC , TOWN ASC

-- ORDER BY DA BİRDEN FAZLA SIRALAMA YAPABİLİRSİN , NAMESURNAME A DAN Z YE CİTY Z DEN A YA TOWN DA A DAN Z YE DOĞRU SRALI GELİR

SELECT * FROM CUSTOMER
ORDER BY 5,6

-- ÖNCE 5. KOLONA GÖRE SONRA KENDİ İÇİNDE 6. KOLONA GÖRE SIRALAMA YAPAR

SELECT TOP 2 *
FROM CUSTOMER
WHERE CITY = 'İSTANBUL'
ORDER BY NAMESURNAE DESC

--- ŞEHRİ İSTANBUL OLANLARIN İSİMLERİNE GÖRE TERSTEN SIRALANMIŞLARIN İLK İKİSİNİ GETİR

SELECT TOP 10 PERCENT
* FROM CUSTOMER
ORDER BY AGE

-- EN GENÇ %10 LUK KISMI GETİRİR
