SELECT
([NAMESURNAE],[PHONENUM], [TCNO])
FROM
CUSTOMER
--sadece isim soyisim , telefon ve tc gelir 

SELECT
*
FROM
CUSTOMER
--tüm tabloyu getirir


--TRUNCATE TABLE CUSTOMER
--tüm tablonun verilerini siler


INSERT INTO CUSTOMER
([NAMESURNAE], [GENDER], [BIRTHDATE], [CITY], [TOWN], [PHONENUM], [TCNO])
VALUES
('Aleyna erkul', 'K' , '1916-08-10' , 'Bayburt', 'Tahbur' , '5548513741' ,'48360628368'),
('Gökhan AK', 'E' , '1916-08-10' , 'DÝYARBAKIR', 'merkez' , '5548513741' ,'48360628368')
--TABLOYA VERÝ EKLER

UPDATE CUSTOMER
SET COUNTRY = 'TÜRKÝYE'
--TÜM COUNTRY KOLONLARINI TÜRKÝYE YAPAR

UPDATE CUSTOMER
SET AGE = DATEDIFF(YEAR, BIRTHDATE,GETDATE())
--TÜM TABLONUN AGE KOLONLARINA HESAPLAMA YAPAR

SELECT 
*,DATEDIFF(YEAR, BIRTHDATE,'2024-05-08')
FROM CUSTOMER

--DATEDIFF KOMUTU ÝLE YAÞ HESAPLAR HER KOLONUN

DELETE FROM CUSTOMER
-- TÜM VERÝLERÝ SÝLER TRUNCATE ÝSE TABLONUN ÝLK HALÝNE GERÝ GÝDER AYNI AMA ID DEÐÝÞÝKLÝK OLUR







---WHERE KOMUTU

UPDATE CUSTOMER
SET CITY = 'ÝSTANBUL'
WHERE ID = '3' OR ID = '4';
-- BURADA MESELA ID SÝ 3 VE 4 OLAN SATIRLARIN CITY KOLONLARI ARTIK ÝST OLDU



SELECT * FROM CUSTOMER
WHERE AGE > 30

-- A-YAÞI 30 DAN BÜYÜK OLANLARI GETÝRÝR


SELECT * FROM CUSTOMER
WHERE GENDER = 'K'

--GENDER K OLANLARI GETÝRÝR


SELECT * FROM CUSTOMER
WHERE NAMESURNAE LIKE '%E%'

--NAMEDE S ÝLE BAÞLAYANLARI GETÝRÝR
--S ÝLE BÝTENLERDE 'S%' ÞEKLÝNDE GÖSTERÝLÝR ORTADA YA DA HERHANGÝBÝRYERDE VAR ÝSE '%A%' GÝBÝ YAZILIR




--ÞEHRÝ ÝSTANBUL VE YAÞI 30 OLAN KÝÞÝLER
SELECT * FROM CUSTOMER 
WHERE CITY= 'ÝSTANBUL' AND AGE = 30

SELECT * FROM CUSTOMER 
WHERE GENDER = 'K' AND AGE < 30


SELECT * FROM CUSTOMER 
WHERE CITY = 'ÝSTANBUL' AND TOWN = 'BÜYÜKÇEKMECE' OR TOWN = 'SARIYER'

-- BU DURUMDA ÝSTANBUL- BÜYÜKÇEKMECE VE TOWNU SARIYER LAN TÜM KULLANICILAR GELÝR

SELECT * FROM CUSTOMER 
WHERE CITY = 'ÝSTANBUL' AND (TOWN = 'BÜYÜKÇEKMECE' OR TOWN = 'SARIYER')

--BU DUURMDA ÝSTANBUL-BÜYÜKÇEKMECE VE ÝSTANBUL-SARIYER SADECE GELÝR

UPDATE CUSTOMER 
SET AGEGROUP = 'GENÇ'
WHERE AGE BETWEEN 20 AND 40

--YAÞI 20 ÝLE 40 OLANLARI GENÇ OLARAK ÝÞARETLEDÝK